In [22]:
# Set notebook theme to dark
!jt -t onedork -T -N -fs 10 -nfs 10 -tfs 10 

### Mathematical operations
Python can be used like a simple calculator.

In [41]:
print(4+4)
print(3*4)
print(5/2)

8
12
2.5


### Strings

In [26]:
str1 = "python tutorial"

In [28]:
x = "R"

In [29]:
print("st {} tutorial".format(x))

st R tutorial


In [30]:
len(str1)

15

In [31]:
str1.replace("python", "SQL")

'SQL tutorial'

### Lists
Lists are mutable - they can always be modified. To create lists we use square brackets '[ ]'.

In [34]:
l1 = [4, 7, 10, 13, 16]
type(l1)

list

### Tuples
Tupples are immutable - once created they cannot be modifed 

In [35]:
t1 = (1,2)
type(t1)

tuple

### Dictionary
Just like lists, dictionaries are mutable. Each element is a key-value pair. For dictionaries we use curly brackets '{ }'.

In [39]:
d1 = {'key1': 1,
     'key2' : 2,
     'key3' : 3}

In [40]:
type(d1)

dict

### Numpy
Used for numerical computation in Python. Implemented in C and Fortran, hence much faster than Python functions. Contrary to lists, you can insert only one type of values into the array.

In [42]:
import numpy as np

In [43]:
np1 = np.array([1,2,3,4,5])
type(np1)

numpy.ndarray

In [45]:
Mat1 = np.array([[1,2],[3,4]])
Mat1

array([[1, 2],
       [3, 4]])

In [46]:
print(np1.shape)
print(Mat1.shape)

(5,)
(2, 2)


In [48]:
Mat2 = np.arange(0, 10, 1) # We want elements from 0 to 10, with increment of 1
print(Mat2)

[0 1 2 3 4 5 6 7 8 9]


In [49]:
Mat3 = np.linspace(0, 10, 20) # We want 20 elements from 0 to 10 at equal intervals
print(Mat3)

[ 0.          0.52631579  1.05263158  1.57894737  2.10526316  2.63157895
  3.15789474  3.68421053  4.21052632  4.73684211  5.26315789  5.78947368
  6.31578947  6.84210526  7.36842105  7.89473684  8.42105263  8.94736842
  9.47368421 10.        ]


In [51]:
Mat4 = np.random.rand(5,5) # Generate random 5x5 matrix
print(Mat4)

[[0.95237229 0.89153633 0.56549079 0.27784584 0.50128511]
 [0.88897663 0.78045026 0.00851409 0.13290735 0.73857515]
 [0.10442969 0.89654753 0.04866668 0.84118242 0.05913955]
 [0.54596299 0.16355182 0.60644976 0.49026422 0.27847575]
 [0.22331121 0.61139415 0.9789942  0.12998314 0.11699293]]


In [52]:
Mat5 = np.random.randn(5, 5) # Generate random 5x5 matrix with normally distributed values
print(Mat5)

[[-0.84743549 -0.12976096 -1.15199533 -1.11507233 -1.94049251]
 [-0.97292292 -2.14559985 -0.89281677  0.46690166  0.55796129]
 [ 0.9422686   0.17521301 -0.02009109  0.19549853  1.24915176]
 [ 1.52034179  0.59504717 -1.10250478  1.14856559  0.44593166]
 [ 0.06020261 -1.66288102 -1.02073342 -0.71057652  0.55098628]]


In [54]:
print(Mat5[0,0]) # access first row first column value
print(Mat5[0:3,:]) # access first three rows and all the columns

-0.847435492576427
[[-0.84743549 -0.12976096 -1.15199533 -1.11507233 -1.94049251]
 [-0.97292292 -2.14559985 -0.89281677  0.46690166  0.55796129]
 [ 0.9422686   0.17521301 -0.02009109  0.19549853  1.24915176]]


### Pandas
Package for data manipulation.

In [55]:
import pandas as pd

In [64]:
data1 = pd.read_csv("C:\\Users\\b7079552\\OneDrive - Newcastle University\\Maths and coding\\Machine learning\\Machine learning in Python and R\\Data Files\\1. ST Academy - Crash course and Regression files\\Customer.csv", header=0)

In [65]:
data1.head(10)

Customer ID       Customer Name      Segment  Age        Country  \
0    CG-12520         Claire Gute     Consumer   67  United States   
1    DV-13045     Darrin Van Huff    Corporate   31  United States   
2    SO-20335      Sean O'Donnell     Consumer   65  United States   
3    BH-11710     Brosina Hoffman     Consumer   20  United States   
4    AA-10480        Andrew Allen     Consumer   50  United States   
5    IM-15070        Irene Maddox     Consumer   66  United States   
6    HP-14815       Harold Pawlan  Home Office   20  United States   
7    PK-19075           Pete Kriz     Consumer   46  United States   
8    AG-10270     Alejandro Grove     Consumer   18  United States   
9    ZD-21925  Zuschuss Donatelli     Consumer   66  United States   

              City           State  Postal Code   Region  
0        Henderson        Kentucky        42420    South  
1      Los Angeles      California        90036     West  
2  Fort Lauderdale         Florida        33311    South  
3      Los Angeles      California        90032     West  
4          Concord  North Carolina        28027    South  
5          Seattle      Washington        98103     West  
6       Fort Worth           Texas        76106  Central  
7          Madison       Wisconsin        53711  Central  
8      West Jordan            Utah        84084     West  
9    San Francisco      California        94109     West

In [74]:
# Remove index column
data2 = pd.read_csv("C:\\Users\\b7079552\\OneDrive - Newcastle University\\Maths and coding\\Machine learning\\Machine learning in Python and R\\Data Files\\1. ST Academy - Crash course and Regression files\\Customer.csv", header=0, index_col = 0)

In [75]:
data2.head()

Customer Name    Segment  Age        Country             City  \
Customer ID                                                                    
CG-12520         Claire Gute   Consumer   67  United States        Henderson   
DV-13045     Darrin Van Huff  Corporate   31  United States      Los Angeles   
SO-20335      Sean O'Donnell   Consumer   65  United States  Fort Lauderdale   
BH-11710     Brosina Hoffman   Consumer   20  United States      Los Angeles   
AA-10480        Andrew Allen   Consumer   50  United States          Concord   

                      State  Postal Code Region  
Customer ID                                      
CG-12520           Kentucky        42420  South  
DV-13045         California        90036   West  
SO-20335            Florida        33311  South  
BH-11710         California        90032   West  
AA-10480     North Carolina        28027  South

In [76]:
data1.describe()

Age   Postal Code
count  793.000000    793.000000
mean    44.467844  55229.717528
std     15.526673  31679.223816
min     18.000000   1841.000000
25%     31.000000  27217.000000
50%     45.000000  55901.000000
75%     58.000000  90004.000000
max     70.000000  99207.000000